name: Trigger Paystack-MFB Fineract Workflow

on:
  push:
    branches:
      - develop

jobs:
  trigger-workflow:
    name: Trigger Workflow in Paystack-MFB/fineract to fetch upstream changes
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e #v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: Paystack-MFB
          repositories: fineract
          permission-actions: write

      - name: Trigger workflow in Paystack-MFB/fineract
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc #v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repo: Paystack-MFB/fineract
          workflow: fetch-upstream-origin-changes.yml
          ref: main
